server:
  port: 8000

spring:
  application:
    name: msa-gateway-zuul

zuul:
  routes:
    msa-client-app-01:
      path: /app01/**
      url: http://localhost:8081
    msa-client-app-02:
      path: /app02/**
      url: http://localhost:8082

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautZone: http://localhost:8761/eureka